const BASE_URL = import.meta.env.VITE_BASE_URL;
const RECAPTCHA_SITE_KEY = import.meta.env.VITE_RECAPTCHA_SITE_KEY;
const RECAPTCHA_SECRETE_KEY = import.meta.env.VITE_RECAPTCHA_SECRETE_KEY

export {BASE_URL ,RECAPTCHA_SITE_KEY, RECAPTCHA_SECRETE_KEY};